#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : font-bitstream-type1
Version  : 1.0.3
Release  : 5
URL      : http://xorg.freedesktop.org/releases/individual/font/font-bitstream-type1-1.0.3.tar.gz
Source0  : http://xorg.freedesktop.org/releases/individual/font/font-bitstream-type1-1.0.3.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: font-bitstream-type1-data
BuildRequires : mkfontdir-bin
BuildRequires : mkfontscale-bin
BuildRequires : pkgconfig(fontutil)
BuildRequires : pkgconfig(xorg-macros)

%description
All questions regarding this software should be directed at the
Xorg mailing list:

%package data
Summary: data components for the font-bitstream-type1 package.
Group: Data

%description data
data components for the font-bitstream-type1 package.


%prep
%setup -q -n font-bitstream-type1-1.0.3

%build
%configure --disable-static
make V=1 %{?_smp_mflags}

%check
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/fonts/X11/Type1/c0419bt_.afm
/usr/share/fonts/X11/Type1/c0419bt_.pfb
/usr/share/fonts/X11/Type1/c0582bt_.afm
/usr/share/fonts/X11/Type1/c0582bt_.pfb
/usr/share/fonts/X11/Type1/c0583bt_.afm
/usr/share/fonts/X11/Type1/c0583bt_.pfb
/usr/share/fonts/X11/Type1/c0611bt_.afm
/usr/share/fonts/X11/Type1/c0611bt_.pfb
/usr/share/fonts/X11/Type1/c0632bt_.afm
/usr/share/fonts/X11/Type1/c0632bt_.pfb
/usr/share/fonts/X11/Type1/c0633bt_.afm
/usr/share/fonts/X11/Type1/c0633bt_.pfb
/usr/share/fonts/X11/Type1/c0648bt_.afm
/usr/share/fonts/X11/Type1/c0648bt_.pfb
/usr/share/fonts/X11/Type1/c0649bt_.afm
/usr/share/fonts/X11/Type1/c0649bt_.pfb
/usr/share/fonts/X11/Type1/fonts.dir
/usr/share/fonts/X11/Type1/fonts.scale
